name: gds2x
base: core24
version: '20080229'
summary: Convert integrated circuit gds2 layouts to 3mf/openscad/povray/stl/svg
description: |
  gds2x is a program to take a gds2 layout file and output a POV-Ray scene
  description file of the GDS2 data. This allows the creation of attractive 3D
  pictures of a layout.

grade: stable
confinement: strict

apps:
  gds2x:
    command: bin/gds2x
    plugs: [home]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib

parts:
  lib3mf:
    source: https://github.com/3MFConsortium/lib3mf
    source-type: git
    source-tag: v2.3.2
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
      - -DLIB3MF_TESTS=OFF
      - -DUSE_INCLUDED_LIBZIP=OFF
      - -DUSE_INCLUDED_SSL=OFF
    build-packages:
      - libzip-dev
      - pkg-config
    stage-packages:
      - libzip4t64
    stage:
      - usr/include/Bindings/Cpp/*.hpp
      - usr/include/Bindings/CppDynamic/*.hpp
      - usr/lib/cmake/lib3mf/lib3mfConfig.cmake
      - usr/lib/lib3mf.so*
      - usr/lib/pkgconfig/lib3mf.pc
      - usr/lib/*/libzip.so*
    prime:
      - usr/lib/lib3mf.so*
      - usr/lib/x86_64-linux-gnu
      - usr/lib/*/libzip.so*

  gds2x:
    after:
      - lib3mf
    plugin: cmake
    cmake-parameters:
      - -Dlib3mf_DIR=$SNAPCRAFT_STAGE/usr/lib/cmake/lib3mf
      - -DCMAKE_INSTALL_PREFIX=/
    source: .
    stage-packages:
      - nlohmann-json3-dev
    stage:
      - bin/gds23mf
      - bin/gds2openscad
      - bin/gds2pov
      - bin/gds2svg
      - lib/libgds2x.so*
      - share/gds2x/changes.txt
      - share/gds2x/example.cmd
      - share/gds2x/example.gds
      - share/gds2x/example_process.txt
      - share/gds2x/example_config.txt
      - share/gds2x/readme.txt
